version: "3.8"

services:
  fastify-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      APP_URL: ${APP_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      PORT: 4000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
