import { FastifySchema } from "fastify";

export const createTransactionSchema: FastifySchema = {
  body: {
    type: "object",
    properties: {
      amount: { type: "integer", example: 1000 },
      currency: { type: "string", example: "USD" },
      lang: { type: "string", example: "en" },
      billing: {
        type: "object",
        properties: {
          firstName: { type: "string", example: "John" },
          lastName: { type: "string", example: "Doe" },
          address1: { type: "string", example: "123 Street" },
          city: { type: "string", example: "Cityville" },
          state: { type: "string", example: "State" },
          country: { type: "string", example: "US" },
          postalCode: { type: "string", example: "12345" },
          phone: { type: "string", example: "1234567890" },
          email: { type: "string", example: "john.doe@example.com" },
          externalUserId: { type: "string", example: "user123" },
          dateOfBirth: {
            type: "string",
            format: "date",
            example: "1980-01-01",
          },
        },
        required: [
          "firstName",
          "lastName",
          "address1",
          "city",
          "state",
          "country",
          "postalCode",
          "phone",
          "email",
          "externalUserId",
          "dateOfBirth",
        ],
      },
      orderId: { type: "string", example: "order123" },
      cardToken: { type: "string", example: "token123" },
      payment3dsType: { type: "string", example: "Redirection" },
      kycVerified: { type: "boolean", example: true },
      previousPaymentCount: { type: "integer", example: 5 },
      cardData: {
        type: "object",
        properties: {
          cardNumber: { type: "string", example: "4111111111111111" },
          cardHolderName: { type: "string", example: "John Doe" },
          cardExpiryDate: { type: "string", example: "12" },
          cardExpiryDate2: { type: "string", example: "2024" },
          cardCvv: { type: "string", example: "123" },
          browser: {
            type: "object",
            properties: {
              colorDepth: { type: "integer", example: 24 },
              userAgent: { type: "string", example: "Mozilla/5.0" },
              language: { type: "string", example: "en-US" },
              timeZone: { type: "string", example: "-300" },
              screenWidth: { type: "integer", example: 1920 },
              javaEnabled: { type: "boolean", example: true },
              customerIp: { type: "string", example: "192.168.1.1" },
              screenHeight: { type: "integer", example: 1080 },
              windowHeight: { type: "integer", example: 800 },
              timeZoneOffset: { type: "integer", example: -300 },
              windowWidth: { type: "integer", example: 1200 },
            },
            required: [
              "colorDepth",
              "userAgent",
              "language",
              "timeZone",
              "screenWidth",
              "javaEnabled",
              "customerIp",
              "screenHeight",
              "windowHeight",
              "timeZoneOffset",
              "windowWidth",
            ],
          },
        },
        required: [
          "cardNumber",
          "cardHolderName",
          "cardExpiryDate",
          "cardExpiryDate2",
          "cardCvv",
          "browser",
        ],
      },
      saveCard: { type: "boolean", example: true },
    },
    required: [
      "amount",
      "currency",
      "lang",
      "billing",
      "orderId",
      "cardToken",
      "payment3dsType",
      "kycVerified",
      "previousPaymentCount",
      "cardData",
      "saveCard",
    ],
  },
};
