import { FastifySchema } from "fastify";

export const createTransactionSchema: FastifySchema = {
  body: {
    type: "object",
    properties: {
      amount: { type: "integer" },
      currency: { type: "string" },
      lang: { type: "string" },
      billing: {
        type: "object",
        properties: {
          firstName: { type: "string" },
          lastName: { type: "string" },
          address1: { type: "string" },
          city: { type: "string" },
          state: { type: "string" },
          country: { type: "string" },
          postalCode: { type: "string" },
          phone: { type: "string" },
          email: { type: "string" },
          externalUserId: { type: "string" },
          dateOfBirth: {
            type: "string",
            format: "date",
          },
        },
        required: [
          "firstName",
          "lastName",
          "address1",
          "city",
          "state",
          "country",
          "postalCode",
          "phone",
          "email",
          "externalUserId",
          "dateOfBirth",
        ],
      },
      orderId: { type: "string" },
      cardToken: { type: "string" },
      payment3dsType: { type: "string" },
      kycVerified: { type: "boolean" },
      previousPaymentCount: { type: "integer" },
      cardData: {
        type: "object",
        properties: {
          cardNumber: { type: "string" },
          cardHolderName: { type: "string" },
          cardExpiryDate: { type: "string" },
          cardExpiryDate2: { type: "string" },
          cardCvv: { type: "string" },
          browser: {
            type: "object",
            properties: {
              colorDepth: { type: "integer" },
              userAgent: { type: "string" },
              language: { type: "string" },
              timeZone: { type: "string" },
              screenWidth: { type: "integer" },
              javaEnabled: { type: "boolean" },
              customerIp: { type: "string" },
              screenHeight: { type: "integer" },
              windowHeight: { type: "integer" },
              timeZoneOffset: { type: "integer" },
              windowWidth: { type: "integer" },
            },
            required: [
              "colorDepth",
              "userAgent",
              "language",
              "timeZone",
              "screenWidth",
              "javaEnabled",
              "customerIp",
              "screenHeight",
              "windowHeight",
              "timeZoneOffset",
              "windowWidth",
            ],
          },
        },
        required: [
          "cardNumber",
          "cardHolderName",
          "cardExpiryDate",
          "cardExpiryDate2",
          "cardCvv",
          "browser",
        ],
      },
      saveCard: { type: "boolean" },
    },
    required: [
      "amount",
      "currency",
      "lang",
      "billing",
      "orderId",
      "cardToken",
      "payment3dsType",
      "kycVerified",
      "previousPaymentCount",
      "cardData",
      "saveCard",
    ],
  },
};

export const createTransactionSchemssssa: FastifySchema = {
  body: {
    type: "object",
    properties: {
      amount: { type: "integer" },
      currency: { type: "string" },
      lang: { type: "string" },
    },
  },
};
